blank_issues_enabled: false

contact_links:

  - name: SurveySentinel Documentation

    url: https://github.com/SurveySentinel/SurveySentinel-Documentation

    about: Please review the documentation before opening an issue.

  - name: SurveySentinel Legal

    url: https://github.com/SurveySentinel/SurveySentinel-Legal

    about: Licensing and legal documentation.
